---
name: Go
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.11", "1.12", "1.13", "1.14", "1.15", "1.16"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v -race .
